### ISSUE TITLE
Can't read in data from VA Hydro (see "AnalysisCode.R")

### ISSUE THREAD

**Issue by connorb5** [connorb5/USGS_Consumptive_Use#1]
I'm currently having some trouble reading in VA Hydro data. The following command ocassionally works, but a lot of times it says the connection timed out:
VAHydro<-read.csv('http://deq1.bse.vt.edu/d.bet/vahydro_facilities',stringsAsFactors = F)

Does anyone know a better method? Or a way to tell R to try again if it times out?

**Comment by rburghol** [comment]
Not sure what to tell you -- this one loaded in about 10 seconds for me, so I am not sure that R would time out?  HOwever, you may look at the vahydro-1.0 code in the r-dh-ecohydro project to see if some of the timeout settings there help you out.

**Comment by connorb5** [comment]
It's been working today fine, but last week I had to download it manually and then load the download. I'll take a look at the timeout settings and post again if it happens again

**Comment by connorb5** [comment]
Solution is to use DEQ2 rather than DEQ1. Requests will otherwise timeout
