### ISSUE TITLE
VPDES Spreadsheet?

### ISSUE THREAD

**Issue by connorb5** [connorb5/USGS_Consumptive_Use#2]
Does anyone know a different location to access this spreadsheet:
https://www.google.com/url?q=http://www.deq.virginia.gov/Portals/0/DEQ/Water/PollutionDischargeElimination/VPDES%2520Spreadsheets/VPDES%2520Active%2520IP%2520Nov%25202017.xls?ver%3D2017-11-14-152041-490&sa=D&ust=1512674074351000&usg=AFQjCNGfjflxa8aP1DDNW304TUq16koAWA

As is, R is having trouble downloading the spreadsheet from this location using:
download.file('https://www.google.com/url?q=http://www.deq.virginia.gov/Portals/0/DEQ/Water/PollutionDischargeElimination/VPDES%2520Spreadsheets/VPDES%2520Active%2520IP%2520Nov%25202017.xls?ver%3D2017-11-14-152041-490&sa=D&ust=1512674074351000&usg=AFQjCNGfjflxa8aP1DDNW304TUq16koAWA',"C:/Users/connorb5/Desktop/USGS Testing/test.csv")
or
read.csv('https://www.google.com/url?q=http://www.deq.virginia.gov/Portals/0/DEQ/Water/PollutionDischargeElimination/VPDES%2520Spreadsheets/VPDES%2520Active%2520IP%2520Nov%25202017.xls?ver%3D2017-11-14-152041-490&sa=D&ust=1512674074351000&usg=AFQjCNGfjflxa8aP1DDNW304TUq16koAWA')

**Comment by rburghol** [comment]
Looks like the URL is a google search URL, and not resolving to the actual URL, i.e., it is going to google and asking for the file.  Have you tried going directly to: 
http://www.deq.virginia.gov/Portals/0/DEQ/Water/PollutionDischargeElimination/VPDES%20Spreadsheets/VPDES%20Active%20IP%20Nov%202017.xls

NOte that on the VPDES web site where this link occurs, there is a parameter with a date stamp after the URL (todays is ?ver=2017-11-14-152041-490 ), so we may be careful about this.  For example, the current link is actually: http://www.deq.virginia.gov/Portals/0/DEQ/Water/PollutionDischargeElimination/VPDES%20Spreadsheets/VPDES%20Active%20IP%20Nov%202017.xls?ver=2017-11-14-152041-490

**Comment by connorb5** [comment]
Yes, we will have to keep the date in mind moving forward. 

I was able to access it by using the httr package:

> library(httr)
>library(readxl)
>GET('http://www.deq.virginia.gov/Portals/0/DEQ/Water/PollutionDischargeElimination/VPDES%20Spreadsheets/VPDES%20Active%20IP%20Nov%202017.xls?ver=2017-11-14-152041-490', write_disk(temp <- tempfile(fileext = ".xls")))
> VPDESFlows <- read_excel(temp,skip=9)
> VPDESFlows<-VPDESFlows[!is.na(VPDESFlows$Facility),]
